package com.nbadal.libr3;

public enum KnobAssign {
    OFF, PITCH, PRTMENTO, OSC1CTR1, OSC1CTR2, SEMITONE, OSC2TUNE, OSC1LVL, OSC2LVL, NOISELVL, FLT1TYPE, CUTOFF1,
    RESO1, EG1INT1, KEYTRKF1, CUTOFF2, RESO2, EG1INT2, KEYTRKF2, ATTACKF, DECAYF, SUSTAINF, RELEASEF, LEVEL, PAN,
    DEPTHA, ATTACKA, DECAYA, SUSTAINA, RELEASEA, LF1FREQLF1SYNOT, LF2FREQLF2SYNOT, VPTC1NT, VPTC2INT, VPTC3INT,
    VPTC4INT, LOWEQGAIN, HIEQGAIN, IFX1KNOB, IFX2KNOB, MFXKNOB, ARPGATE, BASSLVL, DRUMLVL, VOCTHRE, HPFGATE, HPFLVL,
    DIRECTLV, INPUTLVL, TIMB1LVL, VOCDRLVL, FRMNTSFT, FCOFFSET, RESONANC, FCMODINT, EFSENS
}
